config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:create, :destroy, :index]
  resources :contacts
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	mount_uploader :image, ImageUploader
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
end

app/models/send_email.rb
class SendEmail
  require 'sendgrid-ruby'
  include SendGrid

  def self.test_email
    from = Email.new(email: 'na081543@icloud.com') # SendGridの管理画面でSenderに登録したアドレス
    to = Email.new(email: 'na081543@icloud.com') # 送信したいアドレス
    subject = 'テストホゲホゲ'
    content = Content.new(type: 'text/plain', value: 'ハローハロー')
    mail = Mail.new(from, subject, to, content)

    sg = SendGrid::API.new(api_key: ENV['SENDGRID_WEB_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	before_validation { email.downcase! }
	has_secure_password
	validates :password, length: { minimum: 6 }
	mount_uploader :image, ImageUploader
	has_many :pictures
	has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	before_action :login_required

	private

	def login_required
		redirect_to new_session_path unless current_user
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :set_contact, only: [:show, :edit, :update, :destroy]

	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(picture_params)
		if @picture.save
			ContactMailer.contact_mail(@picture).deliver
			redirect_to contacts_path, notice: 'Contact was successfully created.'
		else
			render :new
		end
	end

	def new
	end

	private

	def set_contact
		@contact = Contact.find(params[:id])
	end

	def contact_params
		params.require(:contact).permit(:name, :email, :content)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
	end

	def destroy
		favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
	end

	def index
		@favorites = current_user.favorites
	end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :set_picture, only:[:show, :edit, :update, :destroy]

	def index
		@pictures = Picture.all
	end

	def new
		if params[:back]
			@picture = Picture.new(picture_params)
		else
			@picture = Picture.new
		end
	end

	def destroy
		@picture.destroy
		redirect_to pictures_path, notice:"削除しました！"
	end

	def confirm
		@picture = current_user.pictures.build(picture_params)
		render :new if @picture.invalid?
	end

	def create
		@picture = current_user.pictures.build(picture_params)
		if params[:back]
			render :new
		else
			if @picture.save
				ContactMailer.contact_mail(@picture).deliver
				redirect_to pictures_path, notice: "写真を投稿しました！"
			else
				render :new
			end
		end
	end

	def show
		@picture = Picture.find(params[:id])
		@favorite = current_user.favorites.find_by(picture_id: @picture.id)
	end

	def edit
		#もし本人以外だったら投稿一覧画面に飛ばす　ログインした人のIDと編集しようとしている投稿の投稿者のIDが一致しなかったら
		#ログインした人のID current_user.id
		#編集しようとしている投稿の投稿者のID   @picture.user.id
		@picture = Picture.find(params[:id])
    if current_user.id != @picture.user.id
			redirect_to pictures_path, notice: "あなたはだめよ！"
    end
	end

	def update
		@picture = Picture.find(params[:id])
		if @picture.update(picture_params)
			redirect_to pictures_path, notice: "投稿しました!"
		else
			render :edit
		end
	end

	private

	def picture_params
		params.require(:picture).permit(:content, :image_cache, :image, :user_id)
	end

	def set_picture
		@picture = Picture.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :login_required, only: [:new, :create, :edit, :update]

	def index
	end

	def new
		if params[:back]
			@user = User.new(user_params)
		else
			@user = User.new
		end
	end

	def confirm
		@user = User.new(user_params)
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		#ログインした人のID current_user.id
		#@userはデータベースの中のテーブル名
		@user = User.find(params[:id])
		if current_user.id != @user.id
			redirect_to user_path(@user.id), notice: "編集できません"
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path, notice: "投稿しました!"
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
	def choose_new_or_edit
		if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<p><%= notice %></p>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Image</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.picture.user.name%></td>
    <td><%= favorite.picture.content %></td>
    <td><%= image_tag favorite.picture.image.url, class: "img" if favorite.picture.image.url %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to '新しく写真を投稿する', new_picture_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", users_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
 <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="picture_title">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url, class: "img") if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div> 
<% end %>
<%= link_to "お気に入り一覧にいく", favorites_path %>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
<%= image_tag(@picture.image.url, class: "img") if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>説明文:<%= @picture.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: 'back' %>

<% end %>

app/views/pictures/edit.html.erb
<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>写真一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Image</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.user.name%></td>
    <td><%= picture.content %></td>
    <td><%= image_tag picture.image.url, class: "img" if picture.image_url %></td>
    <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
		<% if logged_in? && current_user.id == picture.user_id %>
      <td><%= link_to "編集する", edit_picture_path(picture.id), date: { confirm: "本当に編集していいですか？"} %></td>
		  <td><%= link_to '削除する', picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
    <% end %>
  </tr>
<% end %>
</table>

<br>

<%= link_to '新しく写真を投稿する', new_picture_path %>
<%= link_to 'お気に入り一覧にいく', favorites_path %>

app/views/pictures/new.html.erb
 <h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<h1>写真詳細画面</h1>
<p>内容: <%= @picture.content %></p>
<%= image_tag @picture.image.url %>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>
<%= link_to '一覧画面に戻る', pictures_path %>

app/views/users/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <div class="picture">
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>


  <%= f.submit "Create my account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <div class="picture">
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>


  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@user.image.url) if @user.image.present? %>
</p>
<%= link_to 'picture一覧', pictures_path %> |
<%= link_to 'Edit', edit_user_path(@user) %> |